INFO:     172.31.128.57:39316 - "POST /api/v1/documents/upload?organization_id=13 HTTP/1.1" 200 OK
2025-03-11 22:55:01,564 - app.api.v1.document_routes - INFO - Starting background processing for document General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf (ID: 2)
2025-03-11 22:55:01,565 - app.core.services.document_service - INFO - Starting document processing for file: General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf (ID: 2)
2025-03-11 22:55:01,565 - botocore.hooks - DEBUG - Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2025-03-11 22:55:01,567 - botocore.hooks - DEBUG - Changing event name from before-call.apigateway to before-call.api-gateway
2025-03-11 22:55:01,568 - botocore.hooks - DEBUG - Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2025-03-11 22:55:01,568 - botocore.hooks - DEBUG - Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2025-03-11 22:55:01,569 - botocore.hooks - DEBUG - Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2025-03-11 22:55:01,569 - botocore.hooks - DEBUG - Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2025-03-11 22:55:01,569 - botocore.hooks - DEBUG - Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2025-03-11 22:55:01,573 - botocore.hooks - DEBUG - Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2025-03-11 22:55:01,573 - botocore.hooks - DEBUG - Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2025-03-11 22:55:01,573 - botocore.hooks - DEBUG - Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2025-03-11 22:55:01,574 - botocore.hooks - DEBUG - Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2025-03-11 22:55:01,576 - botocore.loaders - DEBUG - Loading JSON file: /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/data/endpoints.json
2025-03-11 22:55:01,725 - botocore.loaders - DEBUG - Loading JSON file: /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/data/sdk-default-configuration.json
2025-03-11 22:55:01,726 - botocore.hooks - DEBUG - Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f2170a9ff60>
2025-03-11 22:55:01,742 - botocore.loaders - DEBUG - Loading JSON file: /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/data/s3/2006-03-01/service-2.json.gz
2025-03-11 22:55:01,749 - botocore.loaders - DEBUG - Loading JSON file: /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/data/s3/2006-03-01/service-2.sdk-extras.json
2025-03-11 22:55:01,762 - botocore.loaders - DEBUG - Loading JSON file: /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/data/s3/2006-03-01/endpoint-rule-set-1.json.gz
2025-03-11 22:55:01,767 - botocore.loaders - DEBUG - Loading JSON file: /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/data/partitions.json
2025-03-11 22:55:01,769 - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f2170a39800>
2025-03-11 22:55:01,769 - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x7f216f63bce0>
2025-03-11 22:55:01,783 - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f2170a39580>
2025-03-11 22:55:01,783 - botocore.configprovider - DEBUG - Looking for endpoint for s3 via: environment_service
2025-03-11 22:55:01,783 - botocore.configprovider - DEBUG - Looking for endpoint for s3 via: environment_global
2025-03-11 22:55:01,784 - botocore.configprovider - DEBUG - Looking for endpoint for s3 via: config_service
2025-03-11 22:55:01,784 - botocore.configprovider - DEBUG - Looking for endpoint for s3 via: config_global
2025-03-11 22:55:01,784 - botocore.configprovider - DEBUG - No configured endpoint found.
2025-03-11 22:55:01,786 - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2025-03-11 22:55:01,789 - botocore.loaders - DEBUG - Loading JSON file: /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/data/_retry.json
2025-03-11 22:55:01,789 - botocore.client - DEBUG - Registering retry handlers for service: s3
2025-03-11 22:55:01,790 - botocore.utils - DEBUG - Registering S3 region redirector handler
2025-03-11 22:55:01,790 - botocore.utils - DEBUG - Registering S3Express Identity Resolver
2025-03-11 22:55:01,791 - boto3.s3.transfer - DEBUG - Opting out of CRT Transfer Manager. Preferred client: auto, CRT available: False, Instance Optimized: False.
2025-03-11 22:55:01,791 - boto3.s3.transfer - DEBUG - Using default client. pid: 6588, thread: 139782005861952
2025-03-11 22:55:01,792 - s3transfer.utils - DEBUG - Acquiring 0
2025-03-11 22:55:01,793 - s3transfer.tasks - DEBUG - UploadSubmissionTask(transfer_id=0, {'transfer_future': <s3transfer.futures.TransferFuture object at 0x7f216eb6bf90>}) about to wait for the following futures []
2025-03-11 22:55:01,793 - s3transfer.tasks - DEBUG - UploadSubmissionTask(transfer_id=0, {'transfer_future': <s3transfer.futures.TransferFuture object at 0x7f216eb6bf90>}) done waiting for dependent futures
2025-03-11 22:55:01,793 - s3transfer.tasks - DEBUG - Executing task UploadSubmissionTask(transfer_id=0, {'transfer_future': <s3transfer.futures.TransferFuture object at 0x7f216eb6bf90>}) with kwargs {'client': <botocore.client.S3 object at 0x7f216f7f95d0>, 'config': <boto3.s3.transfer.TransferConfig object at 0x7f216f433450>, 'osutil': <s3transfer.utils.OSUtils object at 0x7f216ed19210>, 'request_executor': <s3transfer.futures.BoundedExecutor object at 0x7f216eb6b610>, 'transfer_future': <s3transfer.futures.TransferFuture object at 0x7f216eb6bf90>}
2025-03-11 22:55:01,793 - s3transfer.futures - DEBUG - Submitting task PutObjectTask(transfer_id=0, {'bucket': 'pientyai', 'key': 'documents/13/General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf', 'extra_args': {'ChecksumAlgorithm': 'CRC32'}}) to executor <s3transfer.futures.BoundedExecutor object at 0x7f216eb6b610> for transfer request: 0.
2025-03-11 22:55:01,793 - s3transfer.utils - DEBUG - Acquiring 0
2025-03-11 22:55:01,793 - s3transfer.tasks - DEBUG - PutObjectTask(transfer_id=0, {'bucket': 'pientyai', 'key': 'documents/13/General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf', 'extra_args': {'ChecksumAlgorithm': 'CRC32'}}) about to wait for the following futures []
2025-03-11 22:55:01,793 - s3transfer.utils - DEBUG - Releasing acquire 0/None
2025-03-11 22:55:01,793 - s3transfer.tasks - DEBUG - PutObjectTask(transfer_id=0, {'bucket': 'pientyai', 'key': 'documents/13/General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf', 'extra_args': {'ChecksumAlgorithm': 'CRC32'}}) done waiting for dependent futures
2025-03-11 22:55:01,794 - s3transfer.tasks - DEBUG - Executing task PutObjectTask(transfer_id=0, {'bucket': 'pientyai', 'key': 'documents/13/General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf', 'extra_args': {'ChecksumAlgorithm': 'CRC32'}}) with kwargs {'client': <botocore.client.S3 object at 0x7f216f7f95d0>, 'fileobj': <s3transfer.utils.ReadFileChunk object at 0x7f216ec99950>, 'bucket': 'pientyai', 'key': 'documents/13/General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf', 'extra_args': {'ChecksumAlgorithm': 'CRC32'}}
2025-03-11 22:55:01,794 - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function validate_ascii_metadata at 0x7f2170ac6840>
2025-03-11 22:55:01,794 - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function sse_md5 at 0x7f2170ac5b20>
2025-03-11 22:55:01,794 - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function convert_body_to_file_like_object at 0x7f2170ac7240>
2025-03-11 22:55:01,794 - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function validate_bucket_name at 0x7f2170ac5a80>
2025-03-11 22:55:01,794 - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function remove_bucket_from_url_paths_from_model at 0x7f2170ac7c40>
2025-03-11 22:55:01,794 - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <bound method S3RegionRedirectorv2.annotate_request_context of <botocore.utils.S3RegionRedirectorv2 object at 0x7f216e9e4890>>
2025-03-11 22:55:01,794 - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <bound method ClientCreator._inject_s3_input_parameters of <botocore.client.ClientCreator object at 0x7f216ed19c10>>
2025-03-11 22:55:01,794 - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function generate_idempotent_uuid at 0x7f2170ac58a0>
2025-03-11 22:55:01,795 - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function _handle_request_validation_mode_member at 0x7f2170ad0400>
2025-03-11 22:55:01,795 - botocore.hooks - DEBUG - Event before-endpoint-resolution.s3: calling handler <function customize_endpoint_resolver_builtins at 0x7f2170ac7e20>
2025-03-11 22:55:01,795 - botocore.hooks - DEBUG - Event before-endpoint-resolution.s3: calling handler <bound method S3RegionRedirectorv2.redirect_from_cache of <botocore.utils.S3RegionRedirectorv2 object at 0x7f216e9e4890>>
2025-03-11 22:55:01,795 - botocore.regions - DEBUG - Calling endpoint provider with parameters: {'Bucket': 'pientyai', 'Region': 'eu-central-1', 'UseFIPS': False, 'UseDualStack': False, 'ForcePathStyle': False, 'Accelerate': False, 'UseGlobalEndpoint': False, 'Key': 'documents/13/General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf', 'DisableMultiRegionAccessPoints': False, 'UseArnRegion': True}
2025-03-11 22:55:01,796 - botocore.regions - DEBUG - Endpoint provider result: https://pientyai.s3.eu-central-1.amazonaws.com
2025-03-11 22:55:01,796 - botocore.regions - DEBUG - Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
2025-03-11 22:55:01,796 - botocore.regions - DEBUG - Selected auth type "v4" as "v4" with signing context params: {'region': 'eu-central-1', 'signing_name': 's3', 'disableDoubleEncoding': True}
2025-03-11 22:55:01,796 - botocore.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <function add_expect_header at 0x7f2170ac5e40>
2025-03-11 22:55:01,796 - botocore.handlers - DEBUG - Adding expect 100 continue header to request.
2025-03-11 22:55:01,796 - botocore.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <bound method S3ExpressIdentityResolver.apply_signing_cache_key of <botocore.utils.S3ExpressIdentityResolver object at 0x7f216eb6b510>>
2025-03-11 22:55:01,796 - botocore.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <function add_recursion_detection_header at 0x7f2170ac47c0>
2025-03-11 22:55:01,796 - botocore.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <function add_query_compatibility_header at 0x7f2170ad0360>
2025-03-11 22:55:01,796 - botocore.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <function inject_api_version_header_if_needed at 0x7f2170ac7380>
2025-03-11 22:55:01,796 - botocore.endpoint - DEBUG - Making request for OperationModel(name=PutObject) with params: {'url_path': '/documents/13/General%20Terms%20and%20Conditions%20of%20Sale%20KSB%20KGaA%20-%20August%202024%20%281%29.pdf', 'query_string': {}, 'method': 'PUT', 'headers': {'x-amz-sdk-checksum-algorithm': 'CRC32', 'User-Agent': 'Boto3/1.37.6 md/Botocore#1.37.6 ua/2.1 os/linux#6.2.16 md/arch#x86_64 lang/python#3.11.10 md/pyimpl#CPython m/G cfg/retry-mode#legacy Botocore/1.37.6', 'Expect': '100-continue', 'Transfer-Encoding': 'chunked', 'Content-Encoding': 'aws-chunked', 'X-Amz-Trailer': 'x-amz-checksum-crc32', 'X-Amz-Decoded-Content-Length': '189867'}, 'body': <botocore.httpchecksum.AwsChunkedWrapper object at 0x7f216eb70690>, 'auth_path': '/pientyai/documents/13/General%20Terms%20and%20Conditions%20of%20Sale%20KSB%20KGaA%20-%20August%202024%20%281%29.pdf', 'url': 'https://pientyai.s3.eu-central-1.amazonaws.com/documents/13/General%20Terms%20and%20Conditions%20of%20Sale%20KSB%20KGaA%20-%20August%202024%20%281%29.pdf', 'context': {'client_region': 'eu-central-1', 'client_config': <botocore.config.Config object at 0x7f216eb47490>, 'has_streaming_input': True, 'auth_type': 'v4', 'unsigned_payload': None, 's3_redirect': {'redirected': False, 'bucket': 'pientyai', 'params': {'Bucket': 'pientyai', 'Key': 'documents/13/General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf', 'Body': <s3transfer.utils.ReadFileChunk object at 0x7f216ec99950>, 'ChecksumAlgorithm': 'CRC32'}}, 'input_params': {'Bucket': 'pientyai', 'Key': 'documents/13/General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf'}, 'signing': {'region': 'eu-central-1', 'signing_name': 's3', 'disableDoubleEncoding': True}, 'endpoint_properties': {'authSchemes': [{'disableDoubleEncoding': True, 'name': 'sigv4', 'signingName': 's3', 'signingRegion': 'eu-central-1'}]}, 'checksum': {'request_algorithm': {'algorithm': 'crc32', 'in': 'trailer', 'name': 'x-amz-checksum-crc32'}}}}
2025-03-11 22:55:01,797 - botocore.hooks - DEBUG - Event request-created.s3.PutObject: calling handler <function signal_not_transferring at 0x7f216ecbc5e0>
2025-03-11 22:55:01,797 - botocore.hooks - DEBUG - Event request-created.s3.PutObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f216eb47450>>
2025-03-11 22:55:01,797 - botocore.hooks - DEBUG - Event choose-signer.s3.PutObject: calling handler <function set_operation_specific_signer at 0x7f2170ac56c0>
2025-03-11 22:55:01,797 - botocore.hooks - DEBUG - Event before-sign.s3.PutObject: calling handler <function remove_arn_from_signing_path at 0x7f2170ac7d80>
2025-03-11 22:55:01,797 - botocore.hooks - DEBUG - Event before-sign.s3.PutObject: calling handler <function _set_extra_headers_for_unsigned_request at 0x7f2170ad04a0>
2025-03-11 22:55:01,797 - botocore.hooks - DEBUG - Event before-sign.s3.PutObject: calling handler <bound method S3ExpressIdentityResolver.resolve_s3express_identity of <botocore.utils.S3ExpressIdentityResolver object at 0x7f216eb6b510>>
2025-03-11 22:55:01,797 - botocore.auth - DEBUG - Calculating signature using v4 auth.
2025-03-11 22:55:01,797 - botocore.auth - DEBUG - CanonicalRequest:
PUT
/documents/13/General%20Terms%20and%20Conditions%20of%20Sale%20KSB%20KGaA%20-%20August%202024%20%281%29.pdf

content-encoding:aws-chunked
host:pientyai.s3.eu-central-1.amazonaws.com
x-amz-content-sha256:STREAMING-UNSIGNED-PAYLOAD-TRAILER
x-amz-date:20250311T225501Z
x-amz-decoded-content-length:189867
x-amz-sdk-checksum-algorithm:CRC32
x-amz-trailer:x-amz-checksum-crc32

content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length;x-amz-sdk-checksum-algorithm;x-amz-trailer
STREAMING-UNSIGNED-PAYLOAD-TRAILER
2025-03-11 22:55:01,798 - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20250311T225501Z
20250311/eu-central-1/s3/aws4_request
66ebe08e9b21b6eb1bf53868d49718dbfb5c437ae041257ac120bb60c0d37ed0
2025-03-11 22:55:01,798 - botocore.auth - DEBUG - Signature:
498f0f5f2c4722a645dc4453a4c1cf63415a89920c41aa2d0f02e797e5daf64f
2025-03-11 22:55:01,798 - botocore.hooks - DEBUG - Event request-created.s3.PutObject: calling handler <bound method UserAgentString.rebuild_and_replace_user_agent_handler of <botocore.useragent.UserAgentString object at 0x7f216eb5f210>>
2025-03-11 22:55:01,798 - botocore.hooks - DEBUG - Event request-created.s3.PutObject: calling handler <function signal_transferring at 0x7f216ecbca40>
2025-03-11 22:55:01,798 - botocore.hooks - DEBUG - Event request-created.s3.PutObject: calling handler <function add_retry_headers at 0x7f2170ac7ba0>
2025-03-11 22:55:01,798 - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=PUT, url=https://pientyai.s3.eu-central-1.amazonaws.com/documents/13/General%20Terms%20and%20Conditions%20of%20Sale%20KSB%20KGaA%20-%20August%202024%20%281%29.pdf, headers={'x-amz-sdk-checksum-algorithm': b'CRC32', 'User-Agent': b'Boto3/1.37.6 md/Botocore#1.37.6 ua/2.1 os/linux#6.2.16 md/arch#x86_64 lang/python#3.11.10 md/pyimpl#CPython m/G cfg/retry-mode#legacy Botocore/1.37.6', 'Expect': b'100-continue', 'Transfer-Encoding': b'chunked', 'Content-Encoding': b'aws-chunked', 'X-Amz-Trailer': b'x-amz-checksum-crc32', 'X-Amz-Decoded-Content-Length': b'189867', 'X-Amz-Date': b'20250311T225501Z', 'X-Amz-Content-SHA256': b'STREAMING-UNSIGNED-PAYLOAD-TRAILER', 'Authorization': b'AWS4-HMAC-SHA256 Credential=AKIAVFIWJFDEWPEIKYNK/20250311/eu-central-1/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length;x-amz-sdk-checksum-algorithm;x-amz-trailer, Signature=498f0f5f2c4722a645dc4453a4c1cf63415a89920c41aa2d0f02e797e5daf64f', 'amz-sdk-invocation-id': b'328a83dd-3b80-4164-be80-8793fea34135', 'amz-sdk-request': b'attempt=1'}>
2025-03-11 22:55:01,799 - botocore.httpsession - DEBUG - Certificate path: /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/certifi/cacert.pem
2025-03-11 22:55:01,799 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): pientyai.s3.eu-central-1.amazonaws.com:443
2025-03-11 22:55:02,044 - botocore.awsrequest - DEBUG - Waiting for 100 Continue response.
2025-03-11 22:55:02,167 - botocore.awsrequest - DEBUG - Received a non 100 Continue response from the server, NOT sending request body.
2025-03-11 22:55:02,167 - botocore.awsrequest - DEBUG - send() called, but response already received. Not sending data.
2025-03-11 22:55:02,168 - urllib3.connectionpool - DEBUG - https://pientyai.s3.eu-central-1.amazonaws.com:443 "PUT /documents/13/General%20Terms%20and%20Conditions%20of%20Sale%20KSB%20KGaA%20-%20August%202024%20%281%29.pdf HTTP/1.1" 403 None
2025-03-11 22:55:02,168 - botocore.hooks - DEBUG - Event before-parse.s3.PutObject: calling handler <function _handle_200_error at 0x7f2170ad0180>
2025-03-11 22:55:02,169 - botocore.hooks - DEBUG - Event before-parse.s3.PutObject: calling handler <function handle_expires_header at 0x7f2170ac7f60>
2025-03-11 22:55:02,169 - botocore.parsers - DEBUG - Response headers: {'x-amz-request-id': 'N0B0QG4GWKS141P0', 'x-amz-id-2': 'AghGAZQsU4AiPzHf+jPKPO3RAH/frEQCkU6Ze07tQOOu5wiRh+K73FBB5l8VGRvBlAc/Jl+cGIh0DSqoSq7pTqxCqVDPkdWT20WNfkADido=', 'Content-Type': 'application/xml', 'Transfer-Encoding': 'chunked', 'Date': 'Tue, 11 Mar 2025 22:55:01 GMT', 'Connection': 'close', 'Server': 'AmazonS3'}
2025-03-11 22:55:02,169 - botocore.parsers - DEBUG - Response body:
b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>AccessDenied</Code><Message>User: arn:aws:iam::354918410441:user/PientyAIServer is not authorized to perform: s3:PutObject on resource: "arn:aws:s3:::pientyai/documents/13/General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf" because no identity-based policy allows the s3:PutObject action</Message><RequestId>N0B0QG4GWKS141P0</RequestId><HostId>AghGAZQsU4AiPzHf+jPKPO3RAH/frEQCkU6Ze07tQOOu5wiRh+K73FBB5l8VGRvBlAc/Jl+cGIh0DSqoSq7pTqxCqVDPkdWT20WNfkADido=</HostId></Error>'
2025-03-11 22:55:02,171 - botocore.hooks - DEBUG - Event needs-retry.s3.PutObject: calling handler <function _update_status_code at 0x7f2170ad02c0>
2025-03-11 22:55:02,171 - botocore.hooks - DEBUG - Event needs-retry.s3.PutObject: calling handler <botocore.retryhandler.RetryHandler object at 0x7f216eb6b1d0>
2025-03-11 22:55:02,171 - botocore.retryhandler - DEBUG - No retry needed.
2025-03-11 22:55:02,171 - botocore.hooks - DEBUG - Event needs-retry.s3.PutObject: calling handler <bound method S3RegionRedirectorv2.redirect_from_error of <botocore.utils.S3RegionRedirectorv2 object at 0x7f216e9e4890>>
2025-03-11 22:55:02,172 - s3transfer.tasks - DEBUG - Exception raised.
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/s3transfer/tasks.py", line 142, in __call__
    return self._execute_main(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/s3transfer/tasks.py", line 165, in _execute_main
    return_value = self._main(**kwargs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/s3transfer/upload.py", line 796, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/client.py", line 570, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/context.py", line 124, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/client.py", line 1031, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: User: arn:aws:iam::354918410441:user/PientyAIServer is not authorized to perform: s3:PutObject on resource: "arn:aws:s3:::pientyai/documents/13/General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf" because no identity-based policy allows the s3:PutObject action
2025-03-11 22:55:02,173 - s3transfer.utils - DEBUG - Releasing acquire 0/None
2025-03-11 22:55:02,174 - app.core.services.document_service - ERROR - Error uploading file to S3: An error occurred (AccessDenied) when calling the PutObject operation: User: arn:aws:iam::354918410441:user/PientyAIServer is not authorized to perform: s3:PutObject on resource: "arn:aws:s3:::pientyai/documents/13/General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf" because no identity-based policy allows the s3:PutObject action, File: General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf
2025-03-11 22:55:02,174 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-03-11 22:55:02,174 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-03-11 22:55:02,175 INFO sqlalchemy.engine.Engine SELECT files.id, files.fp, files.filename, files.file_type, files.s3_key, files.status, files.file_size, files.created_at, files.updated_at, files.user_id, files.organization_id 
FROM files 
WHERE files.id = $1::INTEGER
2025-03-11 22:55:02,175 - sqlalchemy.engine.Engine - INFO - SELECT files.id, files.fp, files.filename, files.file_type, files.s3_key, files.status, files.file_size, files.created_at, files.updated_at, files.user_id, files.organization_id 
FROM files 
WHERE files.id = $1::INTEGER
2025-03-11 22:55:02,175 INFO sqlalchemy.engine.Engine [generated in 0.00015s] (2,)
2025-03-11 22:55:02,175 - sqlalchemy.engine.Engine - INFO - [generated in 0.00015s] (2,)
2025-03-11 22:55:02,176 - app.api.v1.middlewares.request_logging_middleware - INFO - Request started: GET /api/v1/documents
2025-03-11 22:55:02,176 - app.api.v1.middlewares.request_logging_middleware - DEBUG - Request details: headers={'host': '46c6dd23-92b6-42e0-8441-207276f1a744-00-ypuyupxvbz8d.riker.replit.dev', 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36', 'accept': 'application/json, text/plain, */*', 'accept-encoding': 'gzip, deflate, br, zstd', 'accept-language': 'tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7,la;q=0.6', 'authorization': 'Bearer [REDACTED]', 'origin': 'https://53b27c3e-da65-4fbf-9f03-915d7ef74134-00-1xegreh0l3jg3.kirk.replit.dev', 'referer': 'https://53b27c3e-da65-4fbf-9f03-915d7ef74134-00-1xegreh0l3jg3.kirk.replit.dev/', 'sec-ch-ua': '"Not(A:Brand";v="99", "Google Chrome";v="133", "Chromium";v="133"', 'sec-ch-ua-mobile': '?0', 'sec-ch-ua-platform': '"Windows"', 'sec-fetch-dest': 'empty', 'sec-fetch-mode': 'cors', 'sec-fetch-site': 'cross-site', 'x-forwarded-for': '176.40.242.146, 10.81.3.205', 'x-forwarded-proto': 'https', 'x-replit-user-bio': '', 'x-replit-user-id': '', 'x-replit-user-name': '', 'x-replit-user-profile-image': '', 'x-replit-user-roles': '', 'x-replit-user-teams': '', 'x-replit-user-url': ''}, query_params={'page': '1', 'per_page': '20'}
2025-03-11 22:55:02,177 - app.core.security - DEBUG - Successfully decoded token for user: tunaycl@outlook.com
2025-03-11 22:55:02,336 - app.core.services.redis_service - DEBUG - Successfully retrieved Redis key: user:user_qTSfFwc7HRuRaEqqYwpjiHzdq
2025-03-11 22:55:02,336 - app.core.security - INFO - Retrieved user data from Redis cache for fp: user_qTSfFwc7HRuRaEqqYwpjiHzdq
2025-03-11 22:55:02,336 - app.api.v1.auth - DEBUG - Using cached user data for fp: user_qTSfFwc7HRuRaEqqYwpjiHzdq
2025-03-11 22:55:02,336 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-03-11 22:55:02,336 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-03-11 22:55:02,337 INFO sqlalchemy.engine.Engine SELECT users.id, users.fp, users.email, users.hashed_password, users.full_name, users.role, users.is_active, users.last_login, users.created_at, users.updated_at 
FROM users 
WHERE users.fp = $1::VARCHAR
2025-03-11 22:55:02,337 - sqlalchemy.engine.Engine - INFO - SELECT users.id, users.fp, users.email, users.hashed_password, users.full_name, users.role, users.is_active, users.last_login, users.created_at, users.updated_at 
FROM users 
WHERE users.fp = $1::VARCHAR
2025-03-11 22:55:02,337 INFO sqlalchemy.engine.Engine [cached since 10.84s ago] ('user_qTSfFwc7HRuRaEqqYwpjiHzdq',)
2025-03-11 22:55:02,337 - sqlalchemy.engine.Engine - INFO - [cached since 10.84s ago] ('user_qTSfFwc7HRuRaEqqYwpjiHzdq',)
2025-03-11 22:55:02,492 INFO sqlalchemy.engine.Engine UPDATE files SET status=$1::filestatus, updated_at=now() WHERE files.id = $2::INTEGER
2025-03-11 22:55:02,492 - sqlalchemy.engine.Engine - INFO - UPDATE files SET status=$1::filestatus, updated_at=now() WHERE files.id = $2::INTEGER
2025-03-11 22:55:02,492 INFO sqlalchemy.engine.Engine [generated in 0.00022s] ('FAILED', 2)
2025-03-11 22:55:02,492 - sqlalchemy.engine.Engine - INFO - [generated in 0.00022s] ('FAILED', 2)
2025-03-11 22:55:02,651 INFO sqlalchemy.engine.Engine SELECT users_1.id AS users_1_id, organizations.id AS organizations_id, organizations.name AS organizations_name, organizations.description AS organizations_description, organizations.created_at AS organizations_created_at, organizations.updated_at AS organizations_updated_at 
FROM users AS users_1 JOIN user_organizations AS user_organizations_1 ON users_1.id = user_organizations_1.user_id JOIN organizations ON organizations.id = user_organizations_1.organization_id 
WHERE users_1.id IN ($1::INTEGER)
2025-03-11 22:55:02,651 - sqlalchemy.engine.Engine - INFO - SELECT users_1.id AS users_1_id, organizations.id AS organizations_id, organizations.name AS organizations_name, organizations.description AS organizations_description, organizations.created_at AS organizations_created_at, organizations.updated_at AS organizations_updated_at 
FROM users AS users_1 JOIN user_organizations AS user_organizations_1 ON users_1.id = user_organizations_1.user_id JOIN organizations ON organizations.id = user_organizations_1.organization_id 
WHERE users_1.id IN ($1::INTEGER)
2025-03-11 22:55:02,651 INFO sqlalchemy.engine.Engine [cached since 9.694s ago] (1,)
2025-03-11 22:55:02,651 - sqlalchemy.engine.Engine - INFO - [cached since 9.694s ago] (1,)
2025-03-11 22:55:02,808 - app.api.v1.middlewares.validation_middleware - INFO - Pagination request: page=1, per_page=20
2025-03-11 22:55:02,808 - app.api.v1.document_routes - INFO - Fetching documents for user 1, page 1, per_page 20
2025-03-11 22:55:02,810 INFO sqlalchemy.engine.Engine COMMIT
2025-03-11 22:55:02,810 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-03-11 22:55:02,968 - app.core.services.document_service - INFO - Updated file 2 status to FileStatus.FAILED
2025-03-11 22:55:02,969 - app.core.services.document_service - ERROR - Error in async document processing: An error occurred (AccessDenied) when calling the PutObject operation: User: arn:aws:iam::354918410441:user/PientyAIServer is not authorized to perform: s3:PutObject on resource: "arn:aws:s3:::pientyai/documents/13/General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf" because no identity-based policy allows the s3:PutObject action
Traceback (most recent call last):
  File "/home/runner/workspace/app/core/services/document_service.py", line 121, in process_document_async
    self.s3_client.upload_fileobj(
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/context.py", line 124, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/boto3/s3/inject.py", line 670, in upload_fileobj
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/s3transfer/futures.py", line 111, in result
    return self._coordinator.result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/s3transfer/futures.py", line 272, in result
    raise self._exception
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/s3transfer/tasks.py", line 142, in __call__
    return self._execute_main(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/s3transfer/tasks.py", line 165, in _execute_main
    return_value = self._main(**kwargs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/s3transfer/upload.py", line 796, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/client.py", line 570, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/context.py", line 124, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/client.py", line 1031, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: User: arn:aws:iam::354918410441:user/PientyAIServer is not authorized to perform: s3:PutObject on resource: "arn:aws:s3:::pientyai/documents/13/General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf" because no identity-based policy allows the s3:PutObject action
2025-03-11 22:55:02,970 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-03-11 22:55:02,970 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-03-11 22:55:02,970 INFO sqlalchemy.engine.Engine SELECT files.id, files.fp, files.filename, files.file_type, files.s3_key, files.status, files.file_size, files.created_at, files.updated_at, files.user_id, files.organization_id 
FROM files 
WHERE files.id = $1::INTEGER
2025-03-11 22:55:02,970 - sqlalchemy.engine.Engine - INFO - SELECT files.id, files.fp, files.filename, files.file_type, files.s3_key, files.status, files.file_size, files.created_at, files.updated_at, files.user_id, files.organization_id 
FROM files 
WHERE files.id = $1::INTEGER
2025-03-11 22:55:02,971 INFO sqlalchemy.engine.Engine [cached since 0.7955s ago] (2,)
2025-03-11 22:55:02,971 - sqlalchemy.engine.Engine - INFO - [cached since 0.7955s ago] (2,)
2025-03-11 22:55:03,289 INFO sqlalchemy.engine.Engine COMMIT
2025-03-11 22:55:03,289 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-03-11 22:55:03,447 - app.core.services.document_service - INFO - Updated file 2 status to FileStatus.FAILED
2025-03-11 22:55:03,447 - app.api.v1.document_routes - ERROR - Background document processing failed: An error occurred (AccessDenied) when calling the PutObject operation: User: arn:aws:iam::354918410441:user/PientyAIServer is not authorized to perform: s3:PutObject on resource: "arn:aws:s3:::pientyai/documents/13/General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf" because no identity-based policy allows the s3:PutObject action
Traceback (most recent call last):
  File "/home/runner/workspace/app/api/v1/document_routes.py", line 118, in process_document_background
    await document_service.process_document_async(
  File "/home/runner/workspace/app/core/services/document_service.py", line 121, in process_document_async
    self.s3_client.upload_fileobj(
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/context.py", line 124, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/boto3/s3/inject.py", line 670, in upload_fileobj
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/s3transfer/futures.py", line 111, in result
    return self._coordinator.result()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/s3transfer/futures.py", line 272, in result
    raise self._exception
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/s3transfer/tasks.py", line 142, in __call__
    return self._execute_main(kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/s3transfer/tasks.py", line 165, in _execute_main
    return_value = self._main(**kwargs)
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/s3transfer/upload.py", line 796, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/client.py", line 570, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/context.py", line 124, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/botocore/client.py", line 1031, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: User: arn:aws:iam::354918410441:user/PientyAIServer is not authorized to perform: s3:PutObject on resource: "arn:aws:s3:::pientyai/documents/13/General Terms and Conditions of Sale KSB KGaA - August 2024 (1).pdf" because no identity-based policy allows the s3:PutObject action
2025-03-11 22:55:03,449 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-03-11 22:55:03,449 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-03-11 22:55:03,449 INFO sqlalchemy.engine.Engine SELECT files.id, files.fp, files.filename, files.file_type, files.s3_key, files.status, files.file_size, files.created_at, files.updated_at, files.user_id, files.organization_id 
FROM files 
WHERE files.id = $1::INTEGER
2025-03-11 22:55:03,449 - sqlalchemy.engine.Engine - INFO - SELECT files.id, files.fp, files.filename, files.file_type, files.s3_key, files.status, files.file_size, files.created_at, files.updated_at, files.user_id, files.organization_id 
FROM files 
WHERE files.id = $1::INTEGER
2025-03-11 22:55:03,449 INFO sqlalchemy.engine.Engine [cached since 1.274s ago] (2,)
2025-03-11 22:55:03,449 - sqlalchemy.engine.Engine - INFO - [cached since 1.274s ago] (2,)
2025-03-11 22:55:03,765 INFO sqlalchemy.engine.Engine COMMIT
2025-03-11 22:55:03,765 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-03-11 22:55:03,923 - app.core.services.document_service - INFO - Updated file 2 status to FileStatus.FAILED
2025-03-11 22:55:04,431 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-03-11 22:55:04,431 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)